const BASE_URL = '/cards';

export const CardsEndpoints = {
    BASIC: BASE_URL,
    GET_CARDS: BASE_URL,
    GET_CARD: BASE_URL + '/:cardId',
    DELETE_CARD: BASE_URL + '/:cardId',
    UPDATE_ALIAS: BASE_URL + '/:cardId/alias',
    GET_LIMITS: BASE_URL + '/debitCard/:cardId/limits',
    PUT_LIMITS: BASE_URL + '/:cardId/limits/debit',
    GET_LIMITS_CREDIT: BASE_URL + '/:cardId/limits/credit',
    GET_MOVEMENTS: BASE_URL + '/:cardId/movements',
    GET_MOVEMENT: BASE_URL + '/:cardId/movements/:movementId',
    POST_ACTIVATE_CARD: BASE_URL + '/:cardId/_activate',
    POST_DUPLICATE_CARD: BASE_URL + '/:cardId/_duplicateRequest',
    POST_LOCK_CARD: BASE_URL + '/:cardId/_lock',
    GET_LIMITS_VALUES: BASE_URL + '/standardLimitValues',
    GET_LINKABLE_ACCOUNTS: BASE_URL + '/linkableAccounts',
    GET_ACCOUNTS_ASSOCIATES: BASE_URL + '/:cardId/accounts',
    PUT_ACCOUNTS_ASSOCIATES: BASE_URL + '/:cardId/accounts',
    GET_CREDITCARD_BALANCE: BASE_URL + '/:cardId/balances',
    GET_PAYMENT_TYPES: BASE_URL + '/dataCatalogs/paymentTypes',
    GET_SETTLEMENT_GROUPS: BASE_URL + '/dataCatalogs/settlementGroups',

    GET_STANDARDLIMITVALUES: BASE_URL + '/dataCatalogs/standardLimitValues',
    GET_LOCKREASONTYPE: BASE_URL + '/dataCatalogs/lockReasonTypes',
    GET_PREPAIDSTATUS: BASE_URL + '/dataCatalogs/prepaidStatus',
    PUT_PAYMENT_TYPE: BASE_URL + '/:cardId/paymentType',
    PUT_SETTLEMENT_GROUPS: BASE_URL + '/:cardId/settlementGroup',
    GET_STATEMENTS_STATUS_TYPES: BASE_URL + '/dataCatalogs/statementsStatusTypes',
    GET_STATEMENTS: BASE_URL + '/:cardId/statements',
    GET_STATEMENT: BASE_URL + '/:cardId/statements/:movementId',
    POST_CREDITCARD_PAYMENT: BASE_URL + '/:cardId/_makePayment',
    POST_NEW_CREDITCARD: BASE_URL + '/creditCard/_request',
    POST_NEW_DEBITCARD: BASE_URL + '/debitCard/_request',
    GET_NEW_CREDITCARD_AVAILABLE: BASE_URL + '/products/credit',
    GET_PIN: BASE_URL + '/:cardId/pin',
    GET_CARD_EXPENSES: BASE_URL + '/cards/:cardId/reports/cashflow'
};
