
export const ServerConfig = {
   SERVER_URL: 'http://localhost:3000',
  // SERVER_URL: 'http://10.31.18.15:8085',

  //SERVER_URL: 'http://10.31.18.24:8085',

// SERVER_URL: 'http://10.31.98.15',
  // SERVER_URL: location.protocol + "//" + location.hostname + ((location.port) ? ':' + location.port : ''),

  // PREFIX
  PREFIX_ACCOUNTS: '/api-accounts',
  PREFIX_CARDS: '/api-cards',
  PREFIX_CASH_POOLING: '/api-cash-pooling',
  PREFIX_CHANNEL_SERVICES: '/api-channel-services',
  PREFIX_CHEQUES: '/api-cheques',
  PREFIX_COMMON: '/api-common',
  PREFIX_CONFIRMING: '/api-confirming',
  PREFIX_CONSENTS: '/api-consents',
  PREFIX_CONVERSATIONS: '/api-conversations',
  PREFIX_CREDITS: '/api-credits',
  PREFIX_CUSTOMERS: '/api-customers',
  PREFIX_DEBIN: '/api-debin',
  PREFIX_DEPOSITS: '/api-deposits',
  PREFIX_DIRECT_DEBITS: '/api-direct-debits',
  PREFIX_DOCUMENTS: '/api-documents',
  PREFIX_EXPRESS_BILL: '/api-express-bill',
  PREFIX_EQUITIES: '/api-equities',
  PREFIX_FACTORING: '/api-factoring',
  PREFIX_FOREIGN_OPERATIONS: '/api-foreign-operations',
  PREFIX_FUNDS: '/api-funds',
  PREFIX_LEASING: '/api-leasing',
  PREFIX_LOANS: '/api-loans',
  PREFIX_NOTIFICATIONS: '/api-notifications',
  PREFIX_OTHERS: '/api-others',
  PREFIX_PAYMENTS: '/api-payments',
  PREFIX_PENSIONS: '/api-pensions',
  PREFIX_PHONES: '/api-phones',
  PREFIX_SECURITY: '/api-security',
  PREFIX_SEPA_FILES: '/api-sepa-files',
  PREFIX_SIGNATURES: '/api-signatures',
  PREFIX_TAXES: '/api-taxes',
  PREFIX_TERM_DEPOSITS: '/api-term-deposits',
  PREFIX_TRANSFERS: '/api-transfers',
  PREFIX_USERS: '/api-users',
  PREFIX_UTILS: '/api-utils',
  PREFIX_WITHDRAWALS: '/api-withdrawals'
};
